// AUTO-GENERATED by _build_search.py. Do not edit manually.
window.SEARCH_INDEX = [
    {
    "url": "comm-principle.html",
    "title": "通信原理 · 指定教材",
    "content": "《通信原理》杨洁、王琪，清华大学出版社，ISBN 9787302699514"
  },
  {
    "url": "signal-system.html",
    "title": "信号与系统 · 指定教材",
    "content": "《信号与系统》陈后金，高等教育出版社，ISBN 9787040540222"
  },
  {
    "url": "c-programming.html",
    "title": "C 语言程序设计 · 指定教材",
    "content": "《C语言程序设计（谭浩强）》谭浩强，清华大学出版社，ISBN 9787302653721"
  },
  {
    "url": "mcu.html",
    "title": "单片机原理与应用 · 指定教材",
    "content": "《ARM Cortex-M3嵌入式原理及应用：基于STM32F103微控制器》黄克亚，清华大学出版社，ISBN 9787302538615"
  },
  {
    "url": "data-network.html",
    "title": "数据通信与网络技术 · 指定教材",
    "content": "《数据通信与网络技术》华为技术有限公司，人民邮电出版社，ISBN 9787115558466"
  },
  {
    "url": "mobile-comm.html",
    "title": "移动通信 · 指定教材",
    "content": "《移动通信原理》陈威兵、张刚林，清华大学出版社，ISBN 9787302641124"
  },
  {
    "url": "os-linux.html",
    "title": "操作系统与 Linux · 指定教材",
    "content": "《计算机操作系统（人邮版）》汤小丹 等，人民邮电出版社，ISBN 9787115686572"
  },
  {
    "url": "comm-principle.html",
    "title": "通信原理",
    "content": "通信原理 / 通信原理教程：模拟与数字调制、采样与量化、PCM/编码、同步与跟踪、OFDM 与扩频，含 MATLAB/Python 仿真示例。"
  },
  {
    "url": "comm-principle.html#ch1",
    "title": "第一章 通信系统概述",
    "content": "【通信原理】 通信 ：信息的传输与交换。消息（Message）是信息的载体， 信息（Information） 是消息中不确定性的消除。"
  },
  {
    "url": "comm-principle.html#ch2",
    "title": "第二章 信道与噪声",
    "content": "【通信原理】 调制信道模型： y(t) = k(t)·x(t) + n(t) ，其中 k(t) 为乘性干扰（衰落），n(t) 为加性噪声。"
  },
  {
    "url": "comm-principle.html#ch3",
    "title": "第三章 模拟幅度调制",
    "content": "【通信原理】 要求 |m(t)| max ≤ A（否则过调制失真）。已调波包含 载波 + 上下边带 。"
  },
  {
    "url": "comm-principle.html#ch4",
    "title": "第四章 角度调制（FM / PM）",
    "content": "【通信原理】 小信噪比时包络检波（AM）和 FM 鉴频都出现输出信噪比急剧恶化的 门限效应 。采用锁相环(PLL)鉴频、预加重/去加重可改善门限。"
  },
  {
    "url": "comm-principle.html#ch5",
    "title": "第五章 抽样定理与脉冲调制",
    "content": "【通信原理】 一个频带限制在 [0, f H ] 的模拟信号，可以用间隔 T s = 1/(2f H ) 的离散样值无失真重建。电话语音 f H = 3.4 kHz，取 f s = 8 kHz 留保护带。"
  },
  {
    "url": "comm-principle.html#ch6",
    "title": "第六章 PCM 脉冲编码调制",
    "content": "【通信原理】 模拟信号 → ①抽样(时间离散) → ②量化(幅度离散) → ③编码(二进制表示) → PCM 数字信号 6.2 A律13折线编码 8 位 PCM 码字：极性码 C1 + 段落码 C2C3C4 + 段内码 C5C6C7C8。"
  },
  {
    "url": "comm-principle.html#ch7",
    "title": "第七章 数字基带传输",
    "content": "【通信原理】 理想低通 ：B = R B /2，极限频带利用率 2 Baud/Hz（极限不可实现）； 升余弦滚降 ：B = (1+α)·R B /2，拖尾衰减快、可实现，α 为滚降系数。"
  },
  {
    "url": "comm-principle.html#ch8",
    "title": "第八章 二进制数字调制",
    "content": "【通信原理】 r 为解调器输入信噪比。抗噪声性能： 2PSK > 2FSK > 2ASK 。"
  },
  {
    "url": "comm-principle.html#ch9",
    "title": "第九章 QAM 与高性能调制",
    "content": "【通信原理】 正交幅度调制：I/Q 两路独立的多电平 ASK 正交叠加。16QAM = 4×4 星座，每符号 4 bit。"
  },
  {
    "url": "comm-principle.html#ch10",
    "title": "第十章 信道编码（纠错码）",
    "content": "【通信原理】 (n,k) 码：k 位信息 + r=n−k 位监督。编码效率 R = k/n。"
  },
  {
    "url": "comm-principle.html#ch11",
    "title": "第十一章 同步原理",
    "content": "【通信原理】 利用 巴克码 （如 1110010，自相关旁瓣 ≤1）作帧头，通过相关运算确定帧边界。E1 帧同步码为 0011011。"
  },
  {
    "url": "comm-principle.html#ch12",
    "title": "第十二章 最佳接收与匹配滤波",
    "content": "【通信原理】 匹配滤波器的冲激响应是信号波形的时间反转平移 —— 相关接收机的物理实现。"
  },
  {
    "url": "comm-principle.html#ch13",
    "title": "第十三章 OFDM 与现代通信技术",
    "content": "【通信原理】 宽带信号历经多径 → 频率选择性衰落 → 单载波均衡复杂。OFDM 将宽带信道切成大量 正交窄带子载波 ，每个子载波只经历平坦衰落，均衡极简。"
  },
  {
    "url": "comm-principle.html#ch14",
    "title": "第十四章 习题与思考",
    "content": "【通信原理】 H = ΣP·log₂(1/P) = 1/2×1 + 1/4×2 + 1/8×3 + 1/16×4 + 1/32×5 + 3×(1/64×6)"
  },
  {
    "url": "os-linux.html",
    "title": "操作系统与 Linux",
    "content": "操作系统与 Linux 管理 / 教程：操作系统基本概念、进程/线程、内存管理、文件系统、Linux 常用命令与 Shell 脚本、用户权限与系统运维。"
  },
  {
    "url": "os-linux.html#ch1",
    "title": "第一章 操作系统概述",
    "content": "【操作系统与 Linux】 操作系统（Operating System, OS）是 管理计算机硬件与软件资源 、为用户提供交互接口的系统软件。它是计算机系统的\"内核\"，位于硬件与应用之间。"
  },
  {
    "url": "os-linux.html#ch2",
    "title": "第二章 进程与线程",
    "content": "【操作系统与 Linux】 进程（Process） 是程序在某数据集合上的一次动态执行过程，是OS进行资源分配和调度的基本单位。"
  },
  {
    "url": "os-linux.html#ch3",
    "title": "第三章 CPU调度算法",
    "content": "【操作系统与 Linux】 假设时间片 q = 4，到达与运行时间如下："
  },
  {
    "url": "os-linux.html#ch4",
    "title": "第四章 进程同步与死锁",
    "content": "【操作系统与 Linux】 一段访问共享资源的代码称为 临界区 。解决临界区问题需满足："
  },
  {
    "url": "os-linux.html#ch5",
    "title": "第五章 内存管理",
    "content": "【操作系统与 Linux】 分页把进程的 逻辑地址空间 和 物理内存 都划分为大小相等的\"页/页框\"。"
  },
  {
    "url": "os-linux.html#ch6",
    "title": "第六章 文件系统",
    "content": "【操作系统与 Linux】 文件是一组带名字的相关信息的集合。文件系统负责："
  },
  {
    "url": "os-linux.html#ch7",
    "title": "第七章 Linux入门与常用命令",
    "content": "【操作系统与 Linux】 Windows 上学习 Linux 最简便的方式是装 WSL2 或虚拟机（VMware/VirtualBox）跑 Ubuntu。"
  },
  {
    "url": "os-linux.html#ch8",
    "title": "第八章 用户与权限管理",
    "content": "【操作系统与 Linux】 Linux 是多用户系统。每个用户有 UID，每个用户至少属于一个主组 GID。常见配置文件："
  },
  {
    "url": "os-linux.html#ch9",
    "title": "第九章 Shell脚本编程",
    "content": "【操作系统与 Linux】 Bash （Bourne Again Shell）是 Linux 默认 shell。脚本首行必须是 shebang："
  },
  {
    "url": "os-linux.html#ch10",
    "title": "第十章 进程、网络与服务管理",
    "content": "【操作系统与 Linux】 第十章 进程、网络与服务管理"
  },
  {
    "url": "os-linux.html#ch11",
    "title": "第十一章 习题与思考",
    "content": "【操作系统与 Linux】 第十一章 习题与思考"
  },
  {
    "url": "os-linux.html#ch12",
    "title": "第十二章 实验指导",
    "content": "【操作系统与 Linux】 第十二章 实验指导"
  },
  {
    "url": "os-linux.html#ch13",
    "title": "第十三章 推荐学习资源",
    "content": "【操作系统与 Linux】 第十三章 推荐学习资源"
  },
  {
    "url": "signal-system.html",
    "title": "信号与系统",
    "content": "信号与系统 / 教程：连续与离散信号、LTI 系统、卷积、傅里叶/拉普拉斯/Z 三大变换、滤波器设计、信号流图仿真示例。"
  },
  {
    "url": "signal-system.html#ch1",
    "title": "第一章 信号与系统基本概念",
    "content": "【信号与系统】 第一章 信号与系统基本概念"
  },
  {
    "url": "signal-system.html#ch2",
    "title": "第二章 LTI 系统与卷积",
    "content": "【信号与系统】 步骤：① 翻转 h(τ)→h(−τ) ② 平移 h(t−τ) ③ 相乘 ④ 积分(面积) 关键：确定积分上下限的交界点，分段讨论！ 2.4 因果性与稳定性判据 因果 ⇔ h(t) = 0 (t<0)；稳定 ⇔ ∫|h(t)|dt < ∞（绝对可积） 2.5 卷积的工程意义 系统的零状态响应 = 输入与冲激响应的卷积。任何线性滤波、信道传输、图像模糊，本质都是卷积。FFT 加速卷积（快速卷积）是 DSP 的常用技巧。"
  },
  {
    "url": "signal-system.html#ch3",
    "title": "第三章 傅里叶级数（周期信号）",
    "content": "【信号与系统】 第三章 傅里叶级数（周期信号）"
  },
  {
    "url": "signal-system.html#ch4",
    "title": "第四章 傅里叶变换（非周期信号）",
    "content": "【信号与系统】 物理意义：非周期信号可视为周期 T→∞ 的周期信号，谱线无限密集 → 连续频谱。"
  },
  {
    "url": "signal-system.html#ch5",
    "title": "第五章 傅里叶变换性质与应用",
    "content": "【信号与系统】 乘以 cos ω c t = 频谱左右各搬移 ω c （幅度减半）—— 这就是傅里叶变换频移性质的直接应用，也是通信原理中所有调制的数学本质。"
  },
  {
    "url": "signal-system.html#ch6",
    "title": "第六章 采样定理（抽样定理）",
    "content": "【信号与系统】 抽样 = 信号 × 冲激串 → 频域：原频谱以 ωₛ 为周期进行复制搬移 6.2 奈奎斯特抽样定理 f s ≥ 2f m （信号最高频率）→ 抽样后频谱不混叠，可用低通滤波恢复原信号 f s = 2f m 称 奈奎斯特速率 f s < 2f m → 混叠（aliasing）：高频成分\"伪装\"成低频，不可逆失真 6.3 频域抽样定理（对偶） 对时域采样：时域离散 ↔ 频域周期延拓；对频域采样：频域离散 ↔ 时域周期延拓（DFT 的理论基础）。"
  },
  {
    "url": "signal-system.html#ch7",
    "title": "第七章 拉普拉斯变换",
    "content": "【信号与系统】 拉氏变换 = 广义的傅氏变换（乘 e −σt 强制收敛），能处理 e at u(t) 等增长信号。"
  },
  {
    "url": "signal-system.html#ch8",
    "title": "第八章 Z 变换",
    "content": "【信号与系统】 Z 变换是离散时间信号的\"拉普拉斯变换\"。单位圆上 z = e jω 时退化为离散时间傅里叶变换（DTFT）。"
  },
  {
    "url": "signal-system.html#ch9",
    "title": "第九章 系统函数与稳定性",
    "content": "【信号与系统】 零状态响应下由系统结构唯一决定，与激励无关。"
  },
  {
    "url": "signal-system.html#ch10",
    "title": "第十章 滤波器设计",
    "content": "【信号与系统】 理想低通（矩形幅度特性）物理不可实现（非因果的 sa 冲激响应）。实际滤波器用通带波纹、阻带衰减、过渡带宽三大指标描述。巴特沃斯（最大平坦）、切比雪夫（等波纹）、椭圆（过渡最陡）是三大经典逼近。"
  },
  {
    "url": "signal-system.html#ch11",
    "title": "第十一章 状态变量分析",
    "content": "【信号与系统】 系统能控：rank[B AB … A n−1 B] = n；能观：rank[C; CA; …; CA n−1 ] = n。现代控制理论基石，也是卡尔曼滤波器的理论基础。"
  },
  {
    "url": "signal-system.html#ch12",
    "title": "第十二章 习题与思考",
    "content": "【信号与系统】 y(t) = ∫ 0 t e −2τ dτ · u(t) = (1/2)(1−e −2t )u(t)"
  },
  {
    "url": "c-programming.html",
    "title": "C 语言程序设计",
    "content": "C 语言程序设计 / 教程：C 语言基础语法、流程控制、数组函数、指针与内存、结构体与链表、文件 I/O、常用算法与工程实践。"
  },
  {
    "url": "c-programming.html#ch1",
    "title": "第一章 C语言概述与开发环境",
    "content": "【C 语言程序设计】 第一章 C语言概述与开发环境"
  },
  {
    "url": "c-programming.html#ch2",
    "title": "第二章 数据类型与运算符",
    "content": "【C 语言程序设计】 第二章 数据类型与运算符"
  },
  {
    "url": "c-programming.html#ch3",
    "title": "第三章 输入输出",
    "content": "【C 语言程序设计】 第三章 输入输出"
  },
  {
    "url": "c-programming.html#ch4",
    "title": "第四章 控制结构",
    "content": "【C 语言程序设计】 第四章 控制结构"
  },
  {
    "url": "c-programming.html#ch5",
    "title": "第五章 数组",
    "content": "【C 语言程序设计】 第五章 数组"
  },
  {
    "url": "c-programming.html#ch6",
    "title": "第六章 函数与作用域",
    "content": "【C 语言程序设计】 第六章 函数与作用域"
  },
  {
    "url": "c-programming.html#ch7",
    "title": "第七章 指针（核心中的核心）",
    "content": "【C 语言程序设计】 int a = 10; int *p = &a; /* p存储a的地址; *p就是a本身 */ printf(\"%d %p\\n\", a, p); /* 10, 地址 */ printf(\"%d %p\\n\", *p, &a); /* 10, 同一地址 */ *p = 20; /* 通过指针修改a → a=20 */ ⚠️ 野指针三宗罪 ：①未初始化就解引用 ②free后继续使用(悬垂指针) ③返回局部变量地址。指针错误是段错误(Segmentation Fault)的头号原因。习惯：`int *p = NULL;` 起手，用前判空。 7.2 指针与数组 int a[5] = {1,2,3,4,5"
  },
  {
    "url": "c-programming.html#ch8",
    "title": "第八章 字符串处理",
    "content": "【C 语言程序设计】 第八章 字符串处理"
  },
  {
    "url": "c-programming.html#ch9",
    "title": "第九章 结构体、共用体与枚举",
    "content": "【C 语言程序设计】 第九章 结构体、共用体与枚举"
  },
  {
    "url": "c-programming.html#ch10",
    "title": "第十章 文件操作",
    "content": "【C 语言程序设计】 第十章 文件操作"
  },
  {
    "url": "c-programming.html#ch11",
    "title": "第十一章 链表与数据结构入门",
    "content": "【C 语言程序设计】 第十一章 链表与数据结构入门"
  },
  {
    "url": "c-programming.html#ch12",
    "title": "第十二章 预处理与多文件工程",
    "content": "【C 语言程序设计】 第十二章 预处理与多文件工程"
  },
  {
    "url": "c-programming.html#ch13",
    "title": "第十三章 调试技巧与常见错误",
    "content": "【C 语言程序设计】 第十三章 调试技巧与常见错误"
  },
  {
    "url": "mcu.html",
    "title": "单片机原理与应用",
    "content": "单片机原理与应用 / 教程：51 内核与汇编、C51 编程、中断与定时器、串口/I²C/SPI 总线、ADC/DAC、嵌入式综合项目。"
  },
  {
    "url": "mcu.html#ch1",
    "title": "第一章 单片机概述",
    "content": "【单片机原理与应用】 单片机（MCU，Microcontroller Unit） ：把 CPU、存储器（ROM/RAM）、IO接口、定时器、串口、ADC 等集成在一块芯片上的 微型计算机 。\"麻雀虽小五脏俱全\"。"
  },
  {
    "url": "mcu.html#ch2",
    "title": "第二章 51单片机硬件结构",
    "content": "【单片机原理与应用】 第二章 51单片机硬件结构"
  },
  {
    "url": "mcu.html#ch3",
    "title": "第三章 Keil C51 与开发流程",
    "content": "【单片机原理与应用】 第三章 Keil C51 与开发流程"
  },
  {
    "url": "mcu.html#ch4",
    "title": "第四章 并行IO应用",
    "content": "【单片机原理与应用】 第四章 并行IO应用"
  },
  {
    "url": "mcu.html#ch5",
    "title": "第五章 中断系统",
    "content": "【单片机原理与应用】 CPU 正在干活时，紧急事件发生 → 暂停当前任务 → 转去处理紧急任务（中断服务函数 ISR）→ 处理完返回继续。相比轮询，中断 响应快、效率高、可休眠省电 。"
  },
  {
    "url": "mcu.html#ch6",
    "title": "第六章 定时器/计数器",
    "content": "【单片机原理与应用】 对 机器周期 （12MHz晶振 = 1μs）或外部脉冲计数，从初值加到 65536 溢出（16位方式）→ TF 置位 → 申请中断。"
  },
  {
    "url": "mcu.html#ch7",
    "title": "第七章 串行通信（UART）",
    "content": "【单片机原理与应用】 第七章 串行通信（UART）"
  },
  {
    "url": "mcu.html#ch8",
    "title": "第八章 数码管与键盘",
    "content": "【单片机原理与应用】 第八章 数码管与键盘"
  },
  {
    "url": "mcu.html#ch9",
    "title": "第九章 LCD1602 与 LCD12864",
    "content": "【单片机原理与应用】 第九章 LCD1602 与 LCD12864"
  },
  {
    "url": "mcu.html#ch10",
    "title": "第十章 I2C 与 SPI 总线",
    "content": "【单片机原理与应用】 第十章 I2C 与 SPI 总线"
  },
  {
    "url": "mcu.html#ch11",
    "title": "第十一章 A/D 与 D/A 转换",
    "content": "【单片机原理与应用】 第十一章 A/D 与 D/A 转换"
  },
  {
    "url": "mcu.html#ch12",
    "title": "第十二章 从51到STM32",
    "content": "【单片机原理与应用】 第十二章 从51到STM32"
  },
  {
    "url": "mcu.html#ch13",
    "title": "第十三章 习题与思考",
    "content": "【单片机原理与应用】 机器周期 = 12/12MHz = 1μs。计数值 = 20ms/1μs = 20000。 初值 = 65536 − 20000 = 45536 = 0xB1E0 → TH0 = 0xB1，TL0 = 0xE0。"
  },
  {
    "url": "data-network.html",
    "title": "数据通信与网络",
    "content": "数据通信与网络 / 教程：OSI 七层模型、TCP/IP 协议栈、IP 子网与路由、TCP/UDP、SOCKET 编程、HTTPS/DNS/网络安全。"
  },
  {
    "url": "data-network.html#ch1",
    "title": "第一章 数据通信基础",
    "content": "【数据通信与网络】 第一章 数据通信基础"
  },
  {
    "url": "data-network.html#ch2",
    "title": "第二章 网络体系结构",
    "content": "【数据通信与网络】 第二章 网络体系结构"
  },
  {
    "url": "data-network.html#ch3",
    "title": "第三章 物理层与传输媒介",
    "content": "【数据通信与网络】 第三章 物理层与传输媒介"
  },
  {
    "url": "data-network.html#ch4",
    "title": "第四章 数据链路层与以太网",
    "content": "【数据通信与网络】 例: 数据 101110, 生成多项式 P=1101 (x³+x²+1) 步骤: 数据后补3个0 → 101110000 ÷ 1101 (模2除法,不借位) 余数 = 011 → 发送帧 = 101110 011 接收方: 收到的整串除以P,余数为0 → 无错 4.3 以太网 MAC 帧 前导码(8B) | 目的MAC(6B) | 源MAC(6B) | 类型(2B) | 数据(46~1500B) | FCS(4B) 类型: 0x0800=IP 0x0806=ARP MAC地址: 48位全球唯一, 前24位OUI厂商号 MTU = 1500字节(以太网) 4.4 CSMA/CD 与现代以太网 传"
  },
  {
    "url": "data-network.html#ch5",
    "title": "第五章 交换机与 VLAN",
    "content": "【数据通信与网络】 第五章 交换机与 VLAN"
  },
  {
    "url": "data-network.html#ch6",
    "title": "第六章 网络层与 IP 协议",
    "content": "【数据通信与网络】 第六章 网络层与 IP 协议"
  },
  {
    "url": "data-network.html#ch7",
    "title": "第七章 路由原理与协议",
    "content": "【数据通信与网络】 第七章 路由原理与协议"
  },
  {
    "url": "data-network.html#ch8",
    "title": "第八章 传输层 TCP / UDP",
    "content": "【数据通信与网络】 第八章 传输层 TCP / UDP"
  },
  {
    "url": "data-network.html#ch9",
    "title": "第九章 应用层协议",
    "content": "【数据通信与网络】 递归+迭代查询: 主机 → 本地DNS(递归) → 根 → 顶级域 → 权威DNS(迭代) 记录类型: A(IPv4) AAAA(IPv6) CNAME(别名) MX(邮件) NS(权威) 端口53(UDP为主,长报文用TCP) 9.2 HTTP / HTTPS HTTP/1.1 HTTP/2 HTTP/3 传输 TCP TCP QUIC(UDP) ⭐ 并发 管线化弱 多路复用 多路复用+0-RTT 头压缩 无 HPACK QPACK GET /index.html HTTP/1.1 # 请求方法: GET POST PUT DELETE ... Host: www.example.com #"
  },
  {
    "url": "data-network.html#ch10",
    "title": "第十章 网络安全基础",
    "content": "【数据通信与网络】 第十章 网络安全基础"
  },
  {
    "url": "data-network.html#ch11",
    "title": "第十一章 Socket 编程",
    "content": "【数据通信与网络】 第十一章 Socket 编程"
  },
  {
    "url": "data-network.html#ch12",
    "title": "第十二章 Wireshark 抓包实验",
    "content": "【数据通信与网络】 第十二章 Wireshark 抓包实验"
  },
  {
    "url": "data-network.html#ch13",
    "title": "第十三章 习题与思考",
    "content": "【数据通信与网络】 数据后补3个0：101010000，模2除以1101： 101010000 ÷ 1101 → 余数 = 110 （过程：异或不借位长除） 发送码字 = 101010 110 。接收方整除校验，余数非0即传输出错。"
  },
  {
    "url": "mobile-comm.html",
    "title": "移动通信",
    "content": "移动通信 / 教程：2G/3G/4G/5G 蜂窝演进、多址接入、OFDM、MIMO 与 Massive MIMO、5G NR 架构、6G 发展趋势。"
  },
  {
    "url": "mobile-comm.html#ch1",
    "title": "第一章 移动通信概述",
    "content": "【移动通信】 通信双方 至少一方在移动中 进行信息交换的通信方式。核心挑战：移动性管理、无线信道时变、频谱资源有限、多用户共享。"
  },
  {
    "url": "mobile-comm.html#ch2",
    "title": "第二章 移动信道与电波传播",
    "content": "【移动通信】 移动速度越快、频率越高，多普勒越大，信道变化越快 —— 高铁场景 350km/h 的信道估计是 5G 难题之一。"
  },
  {
    "url": "mobile-comm.html#ch3",
    "title": "第三章 蜂窝组网原理",
    "content": "【移动通信】 用 小功率基站覆盖六边形小区 ，相距足够远的小区 复用同一频率 → 用频率空间复用突破频谱瓶颈，系统容量随小区缩小而增大（\"小区分裂\"）。"
  },
  {
    "url": "mobile-comm.html#ch4",
    "title": "第四章 多址技术",
    "content": "【移动通信】 第四章 多址技术"
  },
  {
    "url": "mobile-comm.html#ch5",
    "title": "第五章 抗衰落技术",
    "content": "【移动通信】 多条独立衰落路径同时传输，\"不把鸡蛋放一个篮子\"。"
  },
  {
    "url": "mobile-comm.html#ch6",
    "title": "第六章 GSM 系统（2G）",
    "content": "【移动通信】 MS(手机: ME+SIM) ←无线接口Um→ BTS(基站) ↕ Abis BSC(基站控制器) ←A→ MSC(移动交换中心) ↕ ↕ ↕ HLR(归属位置寄存器) VLR(拜访) AUC(鉴权) EIR(设备识别) 核心网电路域 + GPRS分组域(SGSN/GGSN) 6.2 GSM 空口关键参数 参数 数值 频段 900/1800MHz（EGSM 890~915上行） 双工方式 FDD（收发相差45MHz） 载波带宽/多址 200kHz，TDMA 8时隙 调制 GMSK（BT=0.3） 语音编码 RPE-LTP 13kbps 信道编码 卷积码 + 交织 6.3 逻辑信道 业务信道 T"
  },
  {
    "url": "mobile-comm.html#ch7",
    "title": "第七章 3G 系统",
    "content": "【移动通信】 第七章 3G 系统"
  },
  {
    "url": "mobile-comm.html#ch8",
    "title": "第八章 4G LTE 与 LTE-Advanced",
    "content": "【移动通信】 第八章 4G LTE 与 LTE-Advanced"
  },
  {
    "url": "mobile-comm.html#ch9",
    "title": "第九章 5G NR 与关键技术",
    "content": "【移动通信】 峰值速率 10~20Gbps | 用户体验速率 100Mbps+ 时延 1ms(空口) | 连接密度 100万/km² 移动性 500km/h | 频谱效率 3~5× 4G | 能效/成本效率 100× 9.3 关键技术 灵活参数集（Numerology） ：子载波间隔 15×2ⁿ kHz（15~240k），适配低时延（大子载波短符号）与广覆盖（小子载波） Massive MIMO ：64/128/256 阵子大规模天线阵列 波束赋形 Beamforming ：能量对准用户而非全向发射，覆盖+容量+干扰控制 毫米波 mmWave ：24~52GHz，带宽数百MHz，覆盖小需密集组网 网络切片 "
  },
  {
    "url": "mobile-comm.html#ch10",
    "title": "第十章 展望 6G",
    "content": "【移动通信】 第十章 展望 6G"
  },
  {
    "url": "mobile-comm.html#ch11",
    "title": "第十一章 标准与产业链",
    "content": "【移动通信】 第十一章 标准与产业链"
  },
  {
    "url": "mobile-comm.html#ch12",
    "title": "第十二章 习题与思考",
    "content": "【移动通信】 v = 108km/h = 30m/s，λ = 3×10⁸/9×10⁸ = 0.333m。 f d = v/λ = 30/0.333 = 90Hz ； T c ≈ 0.423/90 ≈ 4.7ms 。 含义：信道约每 5ms 就明显变化，信道估计/导频密度必须与之匹配。"
  },
  {
    "url": "ee-info.html",
    "title": "电子信息工程",
    "content": "电子信息工程（080701）：电路系统、信号处理、嵌入式与电子设计。详见雉形页。"
  },
  {
    "url": "info-eng.html",
    "title": "信息工程",
    "content": "信息工程（080706）：信息系统与智能信息处理、模式识别、机器学习。详见雉形页。"
  },
  {
    "url": "oe-info.html",
    "title": "光电信息科学与工程",
    "content": "光电信息科学与工程（080705）：光通信、光电子、光电检测与激光。详见雉形页。"
  },
  {
    "url": "index.html",
    "title": "通信工程专业入口",
    "content": "通信工程专业介绍：什么是通信工程、课程体系、就业方向、行业最新动态、技术趋势、常见问题。"
  }
];
